### ISSUE TITLE
GPS Train Tracker

### ISSUE THREAD

**Issue by andrewdex** [Ko-Train/ko-train#9]
Hi guys, What is the feasibility to add a gps tracker for train locating purpose?

**Comment by gayanhewa** [comment]
Unless they already have a tracking mechanism , implementation of something large scale would require the Railway department to get involved and invest.

**Comment by andrewdex** [comment]
Point taken :+1: . Its not a  good idea when considering about the cost of the app. Plus what's the point of crowd-sourcing if we have a gps tracker for the trains..

**Comment by Jehan191924** [comment]
Exactly guys..... I don't think GPS is a good idea to integrate to our app... Yes, we would totally lose the  marketing value..... coz our whole idea is for it to be crowd sourced , and we are selling that

**Comment by gayanhewa** [comment]
The idea has somewhat been around. 
GPS tracking for trains UOM research : http://dl.lib.mrt.ac.lk/handle/123/443

**Comment by pahans** [comment]
what if we can crowed source the GPS tracking too. users can press a button if they are in the train. so the app can detect whether the train is on schedule or not. probably we need to do a feasibility study. but this idea is worth looking at.

**Comment by Jehan191924** [comment]
i think thats a great idea

**Comment by prashanfdo** [comment]
yeahh... its great... Guys we'll create a backlog and put our thoughts in it...

**Comment by andrewdex** [comment]
Nice Ideas guyz... @Jehan191924 yep, we should never go out of focus. :) The only thing that we want to prevent is the false info because if group of people reported a false delay then what would happens?, then we need to handle that. That's what we should focus on right now i guess. @pahans's idea is great if it is feasible. Lets come up with some feasibility study  So we can make it happen. And more ideas how to avoid false info, one suggestion i thought would be to use a gamification system. Yeah @Prashanfdo. we need to have a backlog. Does anyone know any web app for free of course?

**Comment by Jehan191924** [comment]
Guys I am still receiving sms notifications, how is this, @Gayan, are you still having the service from ur phone?

**Comment by andrewdex** [comment]
i didn't get any of it machan. Are you sure are them sms notifications or push notifications ?

**Comment by Jehan191924** [comment]
Yes machn....from Gayans number
